name: Run Tests

# Controls when the action will run.
on: [push, pull_request, workflow_dispatch]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install package and dependencies
        run: pip install .
      - name: Run Tests
        run: ls && pytest --html=test_report.html --self-contained-html --cov-report=html --cov pytransformation tests/
